terraform-infra-eks-cicd

diff --git a/60-eks/Jenkinsfile b/60-eks/Jenkinsfile
--- a/60-eks/Jenkinsfile
+++ b/60-eks/Jenkinsfile
@@ -7,6 +7,7 @@ pipeline {
         REGION = 'us-east-1'
         ACC_ID = '009160060207'
         PROJECT = 'roboshop'
+        CLUSTER  = 'roboshop-dev'
     }
     options {
         timeout(time: 20, unit: 'MINUTES') 
@@ -37,6 +38,27 @@ pipeline {
                     }
                 }
             }
+         stage('Import Cluster If Exists') {
+            steps {
+                script {
+                    dir("60-eks") {
+                        withAWS(credentials: 'aws-creds', region: "${REGION}") {
+                            // Check if cluster exists (returns 0 if found, 254 if not)
+                            def status = sh (
+                                script: "aws eks describe-cluster --name ${CLUSTER} --region ${REGION} >/dev/null 2>&1",
+                                returnStatus: true
+                            )
+                            if (status == 0) {
+                                echo "EKS Cluster ${CLUSTER} exists in AWS. Importing into Terraform state..."
+                                sh "terraform import module.eks.aws_eks_cluster.this[0] ${CLUSTER} || true"
+                            } else {
+                                echo "EKS Cluster ${CLUSTER} not found. Will be created by Terraform."
+                            }
+                        }
+                    }
+                }
+            }
+        }
         stage('plan'){
             steps {
                 script {
